services:
  mysql:
    image: mysql:8.4
    container_name: hospital-mysql
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: HospitalManagement
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uroot",
          "-p$${MYSQL_ROOT_PASSWORD}"
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: hospital-backend
    restart: unless-stopped

    env_file:
      - .env

    environment:
      DB_URL: jdbc:mysql://mysql:3306/HospitalManagement

    ports:
      - "8080:8080"

    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data: